### ISSUE TITLE
Missing HTTPS Redirection

### ISSUE THREAD

**Issue by flowirtz** [openclimatefix/uk-pv-national-gsp-api#105]
**Describe the bug**
Currently we are not redirecting http traffic (port 80) to be https instead (port 443).
This is because of a missing configuration in our Elastic Beanstalk deployment.

The API can already be reached over SSL via https://api.nowcasting.io (or `api-dev` respectively).
Additionally, however, we should be upgrading `http` connections as well.

**To Reproduce**
Steps to reproduce the behaviour:
1) Go to ['...'](http://nowcasting-api-development.eu-west-1.elasticbeanstalk.com/docs)
1) See `Not Secure` in browser navigation bar

**Expected Behaviour**
All connections to `http://nowcasting-api...` get redirected to `https://nowcasting-api...`

**Additional Context**
This can be resolved by [following this AWS Guide](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/configuring-https-httpredirect.html).

**Comment by peterdudfield** [comment]
thanks @flowirtz for putting this together

**Comment by peterdudfield** [comment]
This is no longer an issue
