### ISSUE TITLE
Feedback: Remove rmMode from Location object

### ISSUE THREAD

**Issue by TheLiamGuy** [openclimatefix/uk-pv-national-gsp-api#178]
The Swagger docs currently have a boolean rmMode attribute. According to @peterdudfield this shouldn't be there and is a SQLAlchemy artefact.

**Comment by peterdudfield** [comment]
Thanks @TheLiamGuy for pointing this out

**Comment by peterdudfield** [comment]
This doesnt seem to be in the swagger docs anymore, so ill close this
