### ISSUE TITLE
Move `save_api_call_to_db` to within caching

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/uk-pv-national-gsp-api#236]
## Detailed Description
Would be good to move `save_api_call_to_db` function within the cache. This will make sure all the api requests get saved

## Context
- we save the user and api url to the database

## Possible Implementation
- move function `save_api_call_to_db` to within cache. 
- Not that some routes dont have a `users`, so need to deal with that

**Comment by petermnhull** [comment]
Hi @peterdudfield, I'm happy to take a look at this this week if that's alright with you.

**Comment by peterdudfield** [comment]
ah sorry @petermnhull ive done this already in #240

**Comment by peterdudfield** [comment]
Here's [one](https://github.com/openclimatefix/nowcasting_datamodel/issues/194) you might be able to tackle
