### ISSUE TITLE
Documentation link not working

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/uk-pv-national-gsp-api#258]
The link to the notion page is not working

**Comment by peterdudfield** [comment]
I think its here - https://github.com/openclimatefix/uk-pv-national-gsp-api/blob/main/src/main.py#L93
and it needs `https://`

**Comment by BreakingPitt** [comment]
Hi:

@peterdudfield The link seems to work correctly without changes, it has the https://

So maybe you can close this issue unless there is something more to do.

Best regards

**Comment by peterdudfield** [comment]
interesting, did you run this api locally and try clicking on the link? It doesnt currently work on are api docs - https://api.nowcasting.io/swagger

**Comment by peterdudfield** [comment]
Perhaps its a simple as changing `https:/` to `https://` - https://github.com/openclimatefix/uk-pv-national-gsp-api/blob/main/src/main.py#L93

**Comment by BreakingPitt** [comment]
O_o

I've review it yesterday and I swear that it was correct... :(

I'll change it tomorrow.

Best regards

**Comment by braddf** [comment]
Hey @BreakingPitt – sorry I hadn't seen this until now, but your PR looks like it would have fixed this bug!

Looks like [your PR](https://github.com/openclimatefix/uk-pv-national-gsp-api/pull/277) has been closed/repo was deleted though; if you fancy reopening/re-PR-ing this would be great to merge and credit you, but no worries if not!

**Comment by BreakingPitt** [comment]
Hey @braddf sorry...looks like I've been faster cleaning up the forks in my profile 😂

I'll get it back...
