### ISSUE TITLE
Spike: Refactor GSP/All requests (forecast/truth) to be more DRY 

### ISSUE THREAD

**Issue by braddf** [openclimatefix/uk-pv-national-gsp-api#264]
## Detailed Description
At the moment, GSP-level all forecast/truth responses are very large, and each forecast contains its own set of timestamps for the forecast period along with respective values.
If we were to invert the structure of these, and have forecast timestamps at the top level and then each `gsp_id` as a key to a `forecast_value` (actual implementation may differ), we may save response size, and also could be more like what our own frontend needs for charts etc.

## Context
Should fit our own frontend use cases better, with less data manipulation in the web app, and may be more suitable for other users using our API for similar things – or even completely different things. 
This could also be implemented in parallel to the existing endpoint/return structure, allowing more flexible and specific use of the API data. 

## Possible Implementation
As in description above.

**Comment by peterdudfield** [comment]
Other options could be
- have options to filter on start and end time 
- have options to filter on gsp_ids
- both above?

**Comment by peterdudfield** [comment]
Also could
- reduce variable names
- round numbers

**Comment by braddf** [comment]
E.g. this on the sites API forecast response:

"Long" names: **3.9MB response**
![image](https://github.com/openclimatefix/uk-pv-national-gsp-api/assets/41056982/3cb2a100-92b9-48d9-98cb-d9c137569cdd)

versus "short" names: **2.9MB response**
![image](https://github.com/openclimatefix/uk-pv-national-gsp-api/assets/41056982/fa6898d0-232a-4453-a3ca-94798725687e)

**Comment by peterdudfield** [comment]
> E.g. this on the sites API forecast response:
> 
> "Long" names: **3.9MB response** ![image](https://user-images.githubusercontent.com/41056982/261064429-3cb2a100-92b9-48d9-98cb-d9c137569cdd.png)
> 
> versus "short" names: **2.9MB response** ![image](https://user-images.githubusercontent.com/41056982/261064624-fa6898d0-232a-4453-a3ca-94798725687e.png)

This is good to know. Defiantely a balance of efficent data and making sure its readable. I wonder if we an option in the API called `compact_data` and then that can be used to reduce the amount of data passed

**Comment by peterdudfield** [comment]
> Other options could be
> 
> * have options to filter on start and end time in the api
> * have options to filter on gsp_ids  in the api
> * both above?

We could also filter on lat and lon.

**Comment by peterdudfield** [comment]
Some notes on reducing to 2.d.p

timings [seconds]
dev 27, 13, 28
pro 35, 17, 37

size went down from 1.2MB to 775kb

**Comment by peterdudfield** [comment]
Ill close this for now
