### ISSUE TITLE
Getting 500 Internal Server errors for some queries

### ISSUE THREAD

**Issue by JamieTaylor-TUOS** [openclimatefix/uk-pv-national-gsp-api#295]
## Describe the bug
Seeing `500 internal server errors` for some queries, suspect may be caused by query parameters yielding no data from the DB

## To Reproduce
Steps to reproduce the behaviour:
Query e.g.

https://api.nowcasting.io/v0/solar/GB/gsp/0/forecast?start_datetime_utc=2023-09-21T00:30:00&end_datetime_utc=2023-09-22T00:00:00&creation_limit_utc=2023-09-20T00:00:00

using swagger or Python.

## Expected behaviour
The example query should return forecasted generation where the target datetime is between 2023-09-21T00:30:00 and 2023-09-22T00:00:00 AND the forecast creation time is <= 2023-09-20T00:00:00

If no forecast data exists (i.e. no forecasts made before 2023-09-20T00:00:00 cover the period 2023-09-21T00:30:00 to 2023-09-22T00:00:00). The API should respond with either a 200 status and empty JSON list ... or perhaps a more suitable HTTP error code such as `204 No content`

**Comment by peterdudfield** [comment]
Thanks Jamie, Ill have a look at this. 

Quick fix is 
`https://api.nowcasting.io/v0/solar/GB/gsp/0/forecast?start_datetime_utc=2023-09-20T00:30:00&end_datetime_utc=2023-09-22T00:00:00&creation_limit_utc=2023-09-20T00:00:00`
does seem to work, but Ill look at why the api isnt not working for your request. 

And I agree `204` should be returned if there is not data, but no error

**Comment by peterdudfield** [comment]
Ill close this now as 
`'https://api.quartz.solar/v0/solar/GB/gsp/0/forecast?start_datetime_utc=2024-03-13&end_datetime_utc=2024-03-14&creation_limit_utc=2024-03-12'` 
now works
