### ISSUE TITLE
Add tags to fastapi

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/uk-pv-national-gsp-api#317]
It would be great to add tags to the fastapi

https://fastapi.tiangolo.com/tutorial/metadata/

We could add
- National
- GSP
- System

This would make the api docs give some structure, at the moment it just says default.

**Comment by barkhaaroraa** [comment]
hi, i'd like to work on this

**Comment by peterdudfield** [comment]
Thanks @barkhaaroraa, that would be great

**Comment by peterdudfield** [comment]
This is done now in #322
