### ISSUE TITLE
API: Input Data Last Updated Field incorrect

### ISSUE THREAD

**Issue by zakwatts** [openclimatefix/uk-pv-national-gsp-api#337]
When the "include_metadata" tag is true the following information returns:

`  "inputDataLastUpdated": {
    "gsp": "2023-10-24T16:22:44.812068Z",
    "nwp": "2023-08-29T14:22:49.582920Z",
    "pv": "2023-10-24T16:18:29.611871Z",
    "satellite": "2023-10-24T16:06:39.083938Z"
  }
}`

However these dates look very outdated to today 2024-05-15. Possibly a bug.

**Comment by zakwatts** [comment]
@peterdudfield Do you think this is a bug?

**Comment by peterdudfield** [comment]
yea this is a bug. How important is it for the client?

**Comment by zakwatts** [comment]
No one has mentioned it, I just came across when testing the API.

**Comment by peterdudfield** [comment]
ok, thanks @zakwatts

**Comment by peterdudfield** [comment]
So just checked, 
It looks like, GSP and satellite is wokring, but NWP isnt. This is becasue of the new nwp-consumer. I dont think the right thing it to add it to the nwp-consumer, as that is nice and stand alone. 

Here's some options
1. Add to new nwp-consumer ( not want to do this)
2. Add to airflow, something that hits the database, and updates the `input data last updated`. This is neat and in ariflow, but has the disadvanate, we dont know if the data consumer receieved any new data, or just ran correctly
3. Add endpoint to api, that goes and checks when the GSP, Satellite and NWP was last updated. Need to hide this and maybe add auth0 with scopes. Airflow can then call this after running the data consumer

**Comment by peterdudfield** [comment]
There's another fix thats needed. Some ends point load a latest forecast. These forecast get updated everytime a forecast gets saved. We need to update the input_data_lates_updated as well in [here](https://github.com/openclimatefix/nowcasting_datamodel/blob/main/nowcasting_datamodel/save/update.py#L86)

**Comment by peterdudfield** [comment]
Discuss with @devsjc and @braddf Idea we think we are going to go with is
1. Add enpoint in API that goes and check when the NWP data was last made. Then save to InputDataLastUdpated in the database. 
2. Add auth to this route, scope: write: data_updated and create a auth0 role called admin that is allowed to call this endpoint
3. Add dag in airflow that is triggered at the end of the nwp consuer, that hits this new endpoint in the API

**Comment by peterdudfield** [comment]
This is fixed with `api==1.5.52` and terraform ocf-infrastructure hash of [d0f07f8](https://github.com/openclimatefix/ocf-infrastructure/commit/d0f07f8e5db92c7eafb4d4338fb0e90e7174bc5a)

**Comment by zakwatts** [comment]
Nice, good work!

**Comment by peterdudfield** [comment]
Had to role back https://github.com/openclimatefix/Satip/issues/273, but this is not a problem
