### ISSUE TITLE
Add BMRS national end point

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/uk-pv-national-gsp-api#346]
## Detailed Description
Add a national end point, that provides elexon BMRS solar foreacsts

## Context
- good to compare solar foreast, as users might want both
- https://bmrs.elexon.co.uk/api-documentation/endpoint/forecast/generation/wind-and-solar/day-ahead
- use `elexonpy`

## Possible Implementation
- Use the code - https://github.com/openclimatefix/Elexonpy/blob/main/examples/wind_solar_forecast.py
- Add end point - [here](https://github.com/openclimatefix/uk-pv-national-gsp-api/blob/main/src/national.py)
- End point could be called /v0/solar/GB/national/forecast/bmrs
- parameters would be
-- start_datetime_utc: default - 3 days ago
-- end_datetime_utc: default - 3 days in the future
-- 
<img width="417" alt="Screenshot 2024-07-16 at 13 36 22" src="https://github.com/user-attachments/assets/69084a2a-a999-437d-9a40-fa4b75c2cd20">: default "intraday process". Dont have option for "all"
- dont put auth on it

**Comment by 14Richa** [comment]
Hey @peterdudfield , I can work on this issue.

**Comment by braddf** [comment]
Nice! Does `/v0/solar/GB/national/bmrs` maybe make more sense? Obv these routing rules weren't made with extra forecasts in mind at the time, but being almost as a sub-route of our forecast feels semantically odd to me 😅

**Comment by peterdudfield** [comment]
yea, interesting one. Just to note that BMRS is a forecast, so maybe we could have `/v0/solar/GB/national/bmrs/forecast` or something like that

**Comment by peterdudfield** [comment]
@all-contributors please add @14Richa  for code
