### ISSUE TITLE
Add historic route

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/uk-pv-national-gsp-api#73]
Good to add endpoint that gives the latest forecast of the past

## Detailed Description
Would be nice to see the forecast from yesterday, but just show the last forecast made. 
This is useful for comparing to pvlive 'truth' values. 

Optional inputs can be 'dateFrom' and 'dateTo'. This could default to yesterday to tomorrow

**Comment by JackKelly** [comment]
Good idea!

For accessing "historical forecasts", it might be useful to be able to select the forecast based on _two_ datetimes:

1. The datetime the forecast was created
2. The datetime the forecast is about

e.g. "I want the forecast that was created at 1pm yesterday, which is about 1pm to 4pm yesterday."

**Comment by peterdudfield** [comment]
yea good point, I would go for 'create_before' 1 p.m otherwise we get into funny things like it ran at 1, but was only available at 1.02. 

Then you just fitler for anything created before 1

**Comment by JackKelly** [comment]
Sounds good!

And, in terms of naming, maybe we should adopt the "initialisation_time" name that the NWP community uses? (instead of "creation time"?) Although I really don't strong feelings either way. "creation_time" feels a bit more friendly and understandable, I guess?

**Comment by JackKelly** [comment]
@jacobbieker do you have any thoughts about querying "historical forecasts"? I only ask because you've been playing with lots of NWPs from NOAA. Is there anything that bugs you, or that you particularly like about the namings that NOAA use?!

**Comment by jacobbieker** [comment]
Hmm... Nothing that I can think of off the top of my head, the NOAA NWPs seem to follow the same standard, with a 'valid_time' 'step' time and 'start_time' fields for the datetimes. I somewhat like creation time as the one as it is a bit more friendly, although initialization time is more explicit as to the model was initialized with data at this time. But creation_time also side steps the British English/American English spelling differences too. I kinda like "creation_time" for when its created, and "step" for the amount of time after creation the forecast is for

**Comment by peterdudfield** [comment]
Most routes now have 
- start_datetime_utc
- end_datetime_utc
which work to give historical data
Ill close this for now
